//-->

mm3.SetPosition('relative',0,0);
mm3.SetCorrection(1,0);
mm3.SetCellSpacing(1);
mm3.SetItemDimension(120,35);
mm3.SetBackground('whitesmoke','','','');//whitesmoke
mm3.SetShadow(true,'#0000FF',6);//#E8E8E8
mm3.SetItemText('#000000','left','','','');//black
mm3.SetItemBorder(1,'buttonface','solid');
mm3.SetItemTextHL('#FF0000','left','','','');//#5F8FBF
mm3.SetItemBackgroundHL('#33FF00','','','');
mm3.SetItemBorderHL(1,'black','solid');//1
mm3.SetItemTextClick('black','left','','','');
mm3.SetItemBackgroundClick('buttonface','','','');
mm3.SetItemBorderClick(1,'black','solid');
mm3.SetBorder(0,'navy','solid');
mm3._pop.SetCorrection(1,0);
mm3._pop.SetItemDimension(120,20);
mm3._pop.SetPaddings(1);
mm3._pop.SetBackground('whitesmoke','','','');
mm3._pop.SetSeparator(120,'center','black','');
mm3._pop.SetExpandIcon(true,'++',1);
mm3._pop.SetShadow(true,'#E8E8E8',6);
mm3._pop.SetDelay(800);
mm3._pop.SetItemBorder(0,'#66CCFF','solid');//#66CCFF
mm3._pop.SetItemBorderHL(1,'black','solid');
mm3._pop.SetItemPaddings(1);//1
mm3._pop.SetItemPaddingsHL(0);//0
mm3._pop.SetItemText('black','','','','');
mm3._pop.SetItemTextHL('#FF0000','','','','');//black
mm3._pop.SetItemBackground('','','','');
mm3._pop.SetItemBackgroundHL('#33FF00','','','');//buttonface
mm3.Build();